---
title: "Dinamica del Dolar Paralelo - Argentina"
output: 
  flexdashboard::flex_dashboard:
    theme: cosmo


---


<style>                     
.navbar {
  background-color:black;
  border-color:white;
}
.navbar-brand {
color:white!important;
}
</style>   

<style type="text/css">

.chart-title {  /* chart_title  */
   font-size: 15px

</style>

```{r setup, include=FALSE}

```



```{r}

library(flexdashboard)
library(tidyr)
library(ggplot2)
library(readr)  
library(dplyr)  
library(plotly)
library(readxl)
library(rvest)
library(rsconnect)
library(ggplot2)
library(ggthemes)
library(viridisLite)
library(dplyr)
library(plotly)
library(quantmod)
library(highcharter)
library(tidyverse)
library(miscset)
library(ggplot2)
library(corrplot) 
library(GGally)
library(readr)  
library(dplyr)  
library(crayon) 
library(modeest)
library(readxl)
library(ggthemes)
library(lubridate)
library(gganimate)

```



```{r}

# web scraping



enero20 = as.data.frame(html_table(read_html("https://dolarhistorico.com/cotizacion-dolar-blue/mes/enero-2020")))

febrero20 = as.data.frame(html_table(read_html("https://dolarhistorico.com/cotizacion-dolar-blue/mes/febrero-2020")))

marzo20 = as.data.frame(html_table(read_html("https://dolarhistorico.com/cotizacion-dolar-blue/mes/marzo-2020")))

abril20 = as.data.frame(html_table(read_html("https://dolarhistorico.com/cotizacion-dolar-blue/mes/abril-2020")))

mayo20 = as.data.frame(html_table(read_html("https://dolarhistorico.com/cotizacion-dolar-blue/mes/mayo-2020")))

junio20 = as.data.frame(html_table(read_html("https://dolarhistorico.com/cotizacion-dolar-blue/mes/junio-2020")))

julio20 = as.data.frame(html_table(read_html("https://dolarhistorico.com/cotizacion-dolar-blue/mes/julio-2020")))

agosto20 = as.data.frame(html_table(read_html("https://dolarhistorico.com/cotizacion-dolar-blue/mes/agosto-2020")))

septiembre20 = as.data.frame(html_table(read_html("https://dolarhistorico.com/cotizacion-dolar-blue/mes/septiembre-2020")))

octubre20 = as.data.frame(html_table(read_html("https://dolarhistorico.com/cotizacion-dolar-blue/mes/octubre-2020")))

noviembre20 = as.data.frame(html_table(read_html("https://dolarhistorico.com/cotizacion-dolar-blue/mes/noviembre-2020")))

diciembre20 = as.data.frame(html_table(read_html("https://dolarhistorico.com/cotizacion-dolar-blue/mes/diciembre-2020")))

enero21 = as.data.frame(html_table(read_html("https://dolarhistorico.com/cotizacion-dolar-blue/mes/enero-2021")))

febrero21 = as.data.frame(html_table(read_html("https://dolarhistorico.com/cotizacion-dolar-blue/mes/febrero-2021")))

marzo21 = as.data.frame(html_table(read_html("https://dolarhistorico.com/cotizacion-dolar-blue/mes/marzo-2021")))

abril21 = as.data.frame(html_table(read_html("https://dolarhistorico.com/cotizacion-dolar-blue/mes/abril-2021")))

mayo21 = as.data.frame(html_table(read_html("https://dolarhistorico.com/cotizacion-dolar-blue/mes/mayo-2021")))

junio21 = as.data.frame(html_table(read_html("https://dolarhistorico.com/cotizacion-dolar-blue/mes/junio-2021")))

julio21 = as.data.frame(html_table(read_html("https://dolarhistorico.com/cotizacion-dolar-blue/mes/julio-2021")))

agosto21 = as.data.frame(html_table(read_html("https://dolarhistorico.com/cotizacion-dolar-blue/mes/agosto-2021")))

septiembre21 = as.data.frame(html_table(read_html("https://dolarhistorico.com/cotizacion-dolar-blue/mes/septiembre-2021")))

octubre21 = as.data.frame(html_table(read_html("https://dolarhistorico.com/cotizacion-dolar-blue/mes/octubre-2021")))



dolar = rbind(enero20, febrero20, marzo20, abril20, mayo20, junio20, julio20, agosto20, septiembre20, octubre20, noviembre20, diciembre20, enero21, febrero21, marzo21, abril21, mayo21, junio21, julio21, agosto21, septiembre21,octubre21)

dolar$Variación = NULL

dolar_historico = read_excel('dolar_historico.xlsx')


dolar_historico$Fecha = as.Date(dolar_historico$Fecha)

dolar$Compra = round(as.numeric(gsub(",", ".", dolar$Compra)),2)

dolar$Venta = round(as.numeric(gsub(",", ".", dolar$Venta)),2)

dolar$Promedio = (dolar$Compra + dolar$Venta) / 2

dolar$Fecha = as.Date(dolar$Fecha, format = "%d/%m/%Y")



dolar_final = bind_rows(dolar_historico, dolar)






```



# Time Series


 

Column {.tabset}
-----------------------------------------------------------

### Serie de Tiempo Dinamica del Dolar Paralelo





```{r, warning=FALSE}



dolar_final$Promedio = round(dolar_final$Promedio,2)

dl = dolar_final %>% 
  ggplot(aes(x = Fecha, y = Promedio)) + 
    geom_path(aes(x = Fecha, y = Promedio), alpha = 0.7, size = 1.5, width = 1, color = '#39ad58') + 
    geom_point(aes(x = Fecha, y = Promedio), alpha = 1, size = 4, width = 2,color = 'grey') +
    ggtitle("Regions With Most Cases") +
    scale_x_date(date_labels = "%Y") +
    scale_y_continuous(limits = c(0, 200)) + 
    geom_text(aes(label = paste0("Precio: $",Promedio,'\nPeriodo:',month(dolar_final$Fecha),'/',year(dolar_final$Fecha))), hjust = +1, size = 6) +
    labs(title = 'Dolar Paralelo, Fecha: {frame_along}', x = 'Año', y = 'Dolar Paralelo', subtitle = "Dinamica del Dolar Paralelo",
    caption = "Elaboracion propia en base a datos de Ambito.com") +
    theme_bw() +
    theme(legend.position = "bottom") + 
    transition_reveal(Fecha) +
    geom_vline(xintercept=dolar_final$Fecha[4515],linetype=1, 
                color = "black", size=0.8) +
    annotate(
    geom = "curve",
    x = dolar_final$Fecha[4510],
    y = 82, 
    xend = dolar_final$Fecha[4200],
    yend = 140, 
    curvature = 0, 
    size = 1,
    arrow = arrow(length = unit(2, "mm"))) +
    annotate(geom = "text",
             size = 5,
             x = dolar_final$Fecha[3950],
             y = 155, 
             label = " Inicio de la\nCuarentena\n 20/03/2020", 
             hjust = "left")

animate(dl, nframes = 550, height = 700, width = 1000)







```

